// 网页外壳页面标题与 masthead 指标标签的用户可见文案单一来源。
// 文案 locale 独占门禁：含汉字的字面量只许住在词典文件里，见 scripts/dev/check-ui-i18n.ts。

import type { GoldPathRenderedPage, WorkHubLocale } from "@workhub/ui/gold-path";

export const shellPageTitles: Record<WorkHubLocale, Record<GoldPathRenderedPage["key"], string>> = {
  "zh-CN": {
    home: "总览",
    projects: "项目",
    "project-home": "项目主页",
    "project-timeline": "时间线",
    // NAMING pass：导航项与所有 CTA（新任务）对齐——「接入」是工程词。
    intake: "新任务",
    approvals: "审批",
    workitem: "任务详情",
    proposal: "变更申请",
    conversation: "会话镜像",
    drive: "项目网盘",
    meetings: "会议洞察",
    notifications: "通知中心",
    calendar: "日程",
    health: "项目健康",
    replay: "执行回放",
    cost: "成本",
    agents: "AI 小组",
    knowledge: "知识证据",
    search: "搜索",
    skills: "团队技能",
    settings: "设置",
    memory: "记忆管理"
  },
  "en-US": {
    home: "Overview",
    projects: "Projects",
    "project-home": "Project home",
    "project-timeline": "Timeline",
    intake: "New task",
    approvals: "Approvals",
    workitem: "Task detail",
    proposal: "Change request",
    conversation: "Conversation mirror",
    drive: "Project drive",
    meetings: "Meeting insights",
    notifications: "Notifications",
    calendar: "Calendar",
    health: "Project health",
    replay: "Execution replay",
    cost: "Cost",
    agents: "AI teams",
    knowledge: "Knowledge evidence",
    search: "Search",
    skills: "Team skills",
    settings: "Settings",
    memory: "Memory management"
  }
};

export const metricLabels: Record<WorkHubLocale, Record<string, string>> = {
  "zh-CN": {
    primary: "当前焦点",
    queue: "队列",
    running: "后台运行",
    pending: "待处理",
    requests: "请求",
    trace: "轨迹",
    deliverables: "交付物",
    files: "文件",
    meetings: "会议",
    insights: "洞察",
    unread: "未读",
    done: "已归档",
    overdue: "逾期",
    today: "今日",
    folders: "文件夹",
    versions: "版本",
    evidence: "证据",
    checks: "检查",
    comments: "评论",
    steps: "步骤",
    decisions: "决策",
    snapshots: "还原点",
    tokens: "Tokens",
    cost: "成本",
    budget: "预算",
    agentTeams: "AI 小组",
    autonomy: "自主率",
    options: "选项",
    refs: "来源",
    runtime: "运行时",
    projects: "项目",
    attention: "需要关注",
    critical: "告急",
    openwork: "进行中",
    status: "状态",
    owner: "负责人",
    archived: "已归档",
    events: "事项",
    needsDecision: "需要你决定",
    resolvedInsights: "已处理洞察",
    skillsActive: "激活技能",
    skillsRefined: "已精修",
    skillsAiAuthored: "AI 撰写",
    skillsDeprecated: "已停用",
    memoriesActive: "AI 记住",
    acceptedDeliverables: "已采纳",
    activeProjects: "有进展",
    query: "搜索词",
    messages: "消息",
    milestones: "里程碑"
  },
  "en-US": {
    primary: "Focus",
    queue: "Queue",
    running: "Background",
    pending: "Pending",
    requests: "Requests",
    trace: "Trace",
    deliverables: "Deliverables",
    files: "Files",
    meetings: "Meetings",
    insights: "Insights",
    unread: "Unread",
    done: "Archived",
    overdue: "Overdue",
    today: "Today",
    folders: "Folders",
    versions: "Versions",
    evidence: "Evidence",
    checks: "Checks",
    comments: "Comments",
    steps: "Steps",
    decisions: "Decisions",
    snapshots: "Restore points",
    tokens: "Tokens",
    cost: "Cost",
    budget: "Budget",
    agentTeams: "AI teams",
    autonomy: "Autonomy",
    options: "Options",
    refs: "Sources",
    runtime: "Runtime",
    projects: "Projects",
    attention: "Attention",
    critical: "Critical",
    openwork: "Open",
    status: "Status",
    owner: "Owner",
    archived: "Archived",
    events: "Events",
    needsDecision: "Needs your decision",
    resolvedInsights: "Resolved insights",
    skillsActive: "Active skills",
    skillsRefined: "Refined",
    skillsAiAuthored: "AI-authored",
    skillsDeprecated: "Deprecated",
    memoriesActive: "AI remembers",
    acceptedDeliverables: "Accepted",
    activeProjects: "Active",
    query: "Query",
    messages: "Messages",
    milestones: "Milestones"
  }
};
