// WorkHub 桌面 · Spotlight 盒子样式（统一玻璃风，依赖 design-system 的 --ds-* token）。
// 一个会生长的玻璃盒：顶部搜索/面包屑 + 内容区（能力网格 ↔ 能力内联页）。原生窗口随内容缩放，
// 故盒子本身不滚动到固定高——内容自然撑高，JS 测高后缩放窗口。盒外/顶栏可拖动 frameless 窗。

export const spotlightCss = [
  // 透明窗：让 OS 毛玻璃(vibrancy/acrylic)透出，盒子是唯一可见玻璃表面。
  "html,body{margin:0;background:transparent!important}",
  "body{overflow:hidden}",
  // 舞台：填满（小）窗口，盒子顶部对齐；四周留白 + 顶栏可拖动整窗。
  ".wh-spot-stage{position:relative;min-height:100vh;box-sizing:border-box;display:flex;flex-direction:column;align-items:stretch;justify-content:flex-start;padding:12px;gap:0;-webkit-app-region:drag}",
  ".wh-spot{position:relative;display:flex;flex-direction:column;border-radius:var(--ds-radius-xl);overflow:hidden;-webkit-app-region:no-drag}",
  // 顶栏：搜索/标题 + 面包屑返回。顶栏空白处可拖动窗（输入/按钮 no-drag）。
  ".wh-spot-top{display:flex;align-items:center;gap:10px;padding:12px 14px;border-bottom:1px solid var(--ds-glass-hairline);-webkit-app-region:drag}",
  ".wh-spot-top>*{-webkit-app-region:no-drag}",
  ".wh-spot-back{display:none;align-items:center;justify-content:center;width:30px;height:30px;flex:0 0 auto;border:1px solid var(--ds-glass-border);border-radius:var(--ds-radius-pill);background:var(--ds-glass);color:var(--ds-ink-muted);cursor:pointer;transition:transform var(--ds-dur-fast) var(--ds-spring),color var(--ds-dur-fast) var(--ds-ease),background var(--ds-dur-fast) var(--ds-ease)}",
  ".wh-spot-back:hover{color:var(--ds-ink);background:rgba(255,255,255,.72)}.wh-spot-back:active{transform:scale(.9)}.wh-spot-back svg{width:17px;height:17px}",
  ".wh-spot[data-mode=\"capability\"] .wh-spot-back{display:inline-flex}",
  // 搜索框（launcher 屏）。
  ".wh-spot-field-wrap{display:flex;align-items:center;gap:10px;flex:1 1 auto;min-width:0}",
  ".wh-spot-field-icon{display:inline-flex;width:18px;height:18px;flex:0 0 auto;color:var(--ds-ink-muted)}.wh-spot-field-icon svg{width:18px;height:18px}",
  ".wh-spot-field{flex:1 1 auto;min-width:0;border:0;background:transparent;outline:none;font:500 16px/1.3 var(--ds-font);color:var(--ds-ink)}",
  ".wh-spot-field::placeholder{color:var(--ds-ink-faint)}",
  // 能力标题（capability 屏）。
  ".wh-spot-titlewrap{display:none;flex-direction:column;gap:1px;min-width:0;flex:1 1 auto}",
  ".wh-spot[data-mode=\"capability\"] .wh-spot-titlewrap{display:flex}",
  ".wh-spot[data-mode=\"capability\"] .wh-spot-field-wrap{display:none}",
  ".wh-spot-title{font:650 16px/1.25 var(--ds-font);color:var(--ds-ink);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
  ".wh-spot-subtitle{font:500 12px/1.2 var(--ds-font);color:var(--ds-ink-muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
  ".wh-spot-kbd{margin-left:auto;flex:0 0 auto;font:700 11px/1 var(--ds-font);color:var(--ds-accent);background:var(--ds-accent-soft);border-radius:6px;padding:4px 7px}",
  ".wh-spot[data-mode=\"capability\"] .wh-spot-kbd{display:none}",
  // 内容区。
  ".wh-spot-body{padding:12px;max-height:min(560px,calc(100vh - 96px));overflow-y:auto;overscroll-behavior:contain}",
  // 能力网格（launcher）。
  ".wh-spot-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}",
  ".wh-spot-cap{display:flex;align-items:center;gap:11px;text-align:left;border:1px solid transparent;background:rgba(255,255,255,.42);border-radius:var(--ds-radius-md);padding:11px 12px;cursor:pointer;color:var(--ds-ink);transition:transform var(--ds-dur-fast) var(--ds-ease-out),background var(--ds-dur-fast) var(--ds-ease),border-color var(--ds-dur-fast) var(--ds-ease),box-shadow var(--ds-dur-fast) var(--ds-ease);will-change:transform}",
  ".wh-spot-cap:hover,.wh-spot-cap[data-active=\"true\"]{background:rgba(255,255,255,.72);border-color:var(--ds-glass-border)}",
  ".wh-spot-cap:hover{transform:translateY(-1px);box-shadow:var(--ds-shadow-1)}",
  ".wh-spot-cap:active{transform:translateY(0) scale(.975)}",
  ".wh-spot-cap[data-active=\"true\"]{box-shadow:inset 0 0 0 2px var(--ds-accent)}",
  // rank17：键盘用户可见焦点环——Tab/聚焦任意盒内可交互元素都给清晰的 accent outline(鼠标点击不触发)。
  ".wh-spot :focus-visible{outline:2px solid var(--ds-accent);outline-offset:2px;border-radius:var(--ds-radius-sm)}",
  ".wh-spot-cap-icon{display:inline-flex;width:24px;height:24px;flex:0 0 auto;color:var(--ds-accent)}.wh-spot-cap-icon svg{width:24px;height:24px}",
  ".wh-spot-cap-text{display:flex;flex-direction:column;gap:1px;min-width:0}",
  ".wh-spot-cap-label{font:600 13.5px/1.25 var(--ds-font);color:var(--ds-ink);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
  ".wh-spot-cap-hint{font:500 11px/1.25 var(--ds-font);color:var(--ds-ink-muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
  ".wh-spot-cap-badge{margin-left:auto;flex:0 0 auto;min-width:18px;height:18px;padding:0 5px;border-radius:999px;background:var(--ds-danger);color:#fff;font:700 11px/18px var(--ds-font);text-align:center}",
  ".wh-spot-empty-grid{padding:20px 8px;text-align:center;color:var(--ds-ink-muted);font:500 13px/1.5 var(--ds-font);grid-column:1 / -1}",
  ".wh-spot-hello{padding:0 2px 11px;font:500 12.5px/1.5 var(--ds-font);color:var(--ds-ink-muted);text-align:center}",
  // 决策卡（审批）。
  ".wh-spot-cards{display:flex;flex-direction:column;gap:10px}",
  ".wh-spot-card{position:relative;display:flex;gap:0;border-radius:var(--ds-radius-lg);overflow:hidden}",
  ".wh-spot-card-bar{flex:0 0 4px;align-self:stretch}",
  ".wh-spot-card-bar--approval{background:linear-gradient(180deg,#7c83ff,#b57bff)}",
  ".wh-spot-card-bar--choice{background:linear-gradient(180deg,#7c83ff,#34c79a)}",
  ".wh-spot-card-bar--permission{background:linear-gradient(180deg,#34c79a,#5fd6a8)}",
  ".wh-spot-card-bar--handoff{background:linear-gradient(180deg,#ff9bb0,#b57bff)}",
  ".wh-spot-card-bar--info{background:linear-gradient(180deg,#b3abce,#c3bce0)}",
  ".wh-spot-card-main{flex:1 1 auto;min-width:0;padding:13px 15px 14px}",
  ".wh-spot-card-head{display:flex;align-items:center;gap:8px}",
  ".wh-spot-chip{font:700 11px/1 var(--ds-font);color:var(--ds-accent);background:var(--ds-accent-soft);border-radius:7px;padding:4px 8px}",
  ".wh-spot-chip--permission{color:var(--ds-success);background:var(--ds-success-soft)}",
  ".wh-spot-chip--handoff{color:var(--ds-danger);background:var(--ds-danger-soft)}",
  ".wh-spot-chip--info{color:var(--ds-ink-muted);background:rgba(255,255,255,.6)}",
  ".wh-spot-card-title{margin:10px 0 0;font:700 15px/1.4 var(--ds-font);color:var(--ds-ink);overflow-wrap:anywhere}",
  ".wh-spot-card-desc{margin:7px 0 0;font:500 13px/1.55 var(--ds-font);color:var(--ds-ink-soft);overflow-wrap:anywhere}",
  ".wh-spot-card-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:13px}",
  ".wh-spot-act{border:1px solid var(--ds-glass-border);border-radius:var(--ds-radius-md);background:rgba(255,255,255,.55);color:var(--ds-ink-soft);font:700 13px/1 var(--ds-font);padding:10px 14px;cursor:pointer;transition:transform var(--ds-dur-fast) var(--ds-spring),filter var(--ds-dur-fast) var(--ds-ease),background var(--ds-dur-fast) var(--ds-ease);will-change:transform}",
  ".wh-spot-act:hover{filter:brightness(1.04)}",
  ".wh-spot-act:active{transform:scale(.96)}",
  ".wh-spot-act--primary{flex:1;min-width:110px;border:0;color:#fff;background:linear-gradient(135deg,#7c83ff,#b57bff);box-shadow:var(--ds-shadow-glow)}",
  ".wh-spot-act--danger{color:var(--ds-danger);border-color:var(--ds-danger-soft)}",
  ".wh-spot-act--quiet{background:rgba(255,255,255,.4);color:var(--ds-ink-muted)}",
  // 打回理由小层。
  ".wh-spot-reasons{margin-top:10px;border-top:1px dashed var(--ds-glass-hairline);padding-top:11px}",
  ".wh-spot-reasons-q{margin:0 0 8px;font:600 12px/1 var(--ds-font);color:var(--ds-ink-muted)}",
  ".wh-spot-reasons-row{display:flex;gap:7px;flex-wrap:wrap}",
  ".wh-spot-reason{border:1px solid var(--ds-glass-border);border-radius:var(--ds-radius-pill);background:rgba(255,255,255,.55);color:var(--ds-ink-soft);font:600 12px/1 var(--ds-font);padding:8px 12px;cursor:pointer;transition:transform var(--ds-dur-fast) var(--ds-spring),border-color var(--ds-dur-fast) var(--ds-ease),color var(--ds-dur-fast) var(--ds-ease)}",
  ".wh-spot-reason:hover{border-color:var(--ds-danger);color:var(--ds-danger)}.wh-spot-reason:active{transform:scale(.95)}",
  // 空/加载/错误/占位。
  ".wh-spot-empty{text-align:center;padding:34px 18px}",
  ".wh-spot-empty-face{font:700 30px/1 var(--ds-font);color:var(--ds-accent)}",
  ".wh-spot-empty-title{margin:14px 0 0;font:800 18px/1.3 var(--ds-font);color:var(--ds-ink)}",
  ".wh-spot-empty-sub{margin:8px 0 0;font:500 13px/1.5 var(--ds-font);color:var(--ds-ink-muted)}",
  ".wh-spot-loading{display:flex;align-items:center;justify-content:center;gap:10px;padding:34px 18px;color:var(--ds-ink-muted);font:600 13px/1 var(--ds-font)}",
  ".wh-spot-spinner{width:16px;height:16px;border-radius:50%;border:2px solid var(--ds-accent-soft);border-top-color:var(--ds-accent);animation:ds-spin .7s linear infinite}",
  "@keyframes ds-spin{to{transform:rotate(360deg)}}",
  ".wh-spot-error{padding:24px 18px;text-align:center;color:var(--ds-ink-muted);font:500 13px/1.5 var(--ds-font)}",
  ".wh-spot-placeholder{text-align:center;padding:30px 20px}",
  ".wh-spot-placeholder-icon{display:inline-flex;width:38px;height:38px;color:var(--ds-accent)}.wh-spot-placeholder-icon svg{width:38px;height:38px}",
  ".wh-spot-placeholder-title{margin:12px 0 0;font:800 18px/1.3 var(--ds-font);color:var(--ds-ink)}",
  ".wh-spot-placeholder-sub{margin:6px 0 0;font:500 13px/1.5 var(--ds-font);color:var(--ds-ink-muted)}",
  ".wh-spot-placeholder-note{margin:14px 0 0;font:500 12.5px/1.6 var(--ds-font);color:var(--ds-ink-faint)}",
  // 派活 / 澄清问答（intake）。
  ".wh-spot-intake{display:flex;flex-direction:column;gap:12px}",
  ".wh-spot-steps{display:flex;flex-wrap:wrap;gap:8px}",
  ".wh-spot-step{display:inline-flex;align-items:center;gap:6px;font:600 11.5px/1 var(--ds-font);color:var(--ds-ink-faint)}",
  ".wh-spot-step-dot{width:7px;height:7px;border-radius:50%;background:var(--ds-glass-border);box-shadow:inset 0 0 0 1px var(--ds-glass-hairline)}",
  ".wh-spot-step--active{color:var(--ds-accent)}.wh-spot-step--active .wh-spot-step-dot{background:var(--ds-accent);box-shadow:0 0 0 3px var(--ds-accent-soft)}",
  ".wh-spot-step--done{color:var(--ds-success)}.wh-spot-step--done .wh-spot-step-dot{background:var(--ds-success)}",
  ".wh-spot-intake-title{margin:0;font:700 17px/1.4 var(--ds-font);color:var(--ds-ink);overflow-wrap:anywhere}",
  ".wh-spot-intake-body{margin:0;font:500 13px/1.6 var(--ds-font);color:var(--ds-ink-soft);overflow-wrap:anywhere}",
  ".wh-spot-opts{display:flex;flex-direction:column;gap:8px}",
  ".wh-spot-opt{display:flex;align-items:flex-start;gap:11px;text-align:left;border:1px solid var(--ds-glass-border);background:rgba(255,255,255,.46);border-radius:var(--ds-radius-md);padding:12px 13px;cursor:pointer;color:var(--ds-ink);transition:transform var(--ds-dur-fast) var(--ds-ease-out),background var(--ds-dur-fast) var(--ds-ease),border-color var(--ds-dur-fast) var(--ds-ease),box-shadow var(--ds-dur-fast) var(--ds-ease);will-change:transform}",
  ".wh-spot-opt:hover{background:rgba(255,255,255,.7);transform:translateY(-1px);box-shadow:var(--ds-shadow-1)}",
  ".wh-spot-opt:active{transform:translateY(0) scale(.985)}",
  ".wh-spot-opt[data-sel=\"true\"]{border-color:var(--ds-accent);background:var(--ds-accent-soft)}",
  ".wh-spot-opt-check{flex:0 0 auto;width:18px;height:18px;margin-top:1px;border-radius:50%;border:2px solid var(--ds-glass-border);transition:all var(--ds-dur-fast)}",
  ".wh-spot-opt[data-sel=\"true\"] .wh-spot-opt-check{border-color:var(--ds-accent);background:var(--ds-accent);box-shadow:inset 0 0 0 3px #fff}",
  ".wh-spot-opt-text{display:flex;flex-direction:column;gap:3px;min-width:0}",
  ".wh-spot-opt-label{display:flex;align-items:center;gap:8px;font:600 13.5px/1.35 var(--ds-font);color:var(--ds-ink);flex-wrap:wrap}",
  ".wh-spot-opt-tag{font:700 10px/1 var(--ds-font);color:var(--ds-accent);background:var(--ds-accent-soft);border-radius:6px;padding:3px 6px}",
  ".wh-spot-opt-desc{font:500 12px/1.5 var(--ds-font);color:var(--ds-ink-muted);overflow-wrap:anywhere}",
  ".wh-spot-freetext{width:100%;box-sizing:border-box;min-height:64px;resize:vertical;border:1px solid var(--ds-glass-border);border-radius:var(--ds-radius-md);background:rgba(255,255,255,.6);color:var(--ds-ink);font:500 13.5px/1.5 var(--ds-font);padding:11px 13px}",
  ".wh-spot-freetext:focus{outline:none;border-color:var(--ds-accent);box-shadow:0 0 0 3px var(--ds-accent-soft)}",
  ".wh-spot-intake-actions{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:2px}",
  ".wh-spot-act:disabled{opacity:.6;cursor:default}",
  // 只读/检索类（项目·成本·日历·知识）。
  ".wh-spot-list{display:flex;flex-direction:column;gap:7px}",
  ".wh-spot-row{display:flex;align-items:center;gap:11px;text-decoration:none;border:1px solid var(--ds-glass-border);background:rgba(255,255,255,.46);border-radius:var(--ds-radius-md);padding:11px 13px;color:var(--ds-ink)}",
  "a.wh-spot-row{transition:transform var(--ds-dur-fast) var(--ds-ease-out),background var(--ds-dur-fast) var(--ds-ease),box-shadow var(--ds-dur-fast) var(--ds-ease);will-change:transform}",
  "a.wh-spot-row:hover{background:rgba(255,255,255,.72);transform:translateY(-1px);box-shadow:var(--ds-shadow-1)}",
  "a.wh-spot-row:active{transform:translateY(0) scale(.985)}",
  ".wh-spot-row-main{flex:1 1 auto;min-width:0;display:flex;flex-direction:column;gap:3px}",
  ".wh-spot-row-title{display:flex;align-items:center;gap:8px;font:600 13.5px/1.3 var(--ds-font);color:var(--ds-ink);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
  ".wh-spot-row-sub{font:500 12px/1.45 var(--ds-font);color:var(--ds-ink-muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
  ".wh-spot-row-tag{font:700 10px/1 var(--ds-font);color:var(--ds-ink-muted);background:rgba(255,255,255,.6);border-radius:6px;padding:3px 6px}",
  ".wh-spot-row-meta{flex:0 0 auto;display:flex;align-items:center;gap:6px;font:700 13px/1 var(--ds-font);color:var(--ds-ink-soft)}",
  ".wh-spot-row-metalabel{font:600 11px/1 var(--ds-font);color:var(--ds-ink-faint)}",
  ".wh-spot-row-badge{min-width:18px;height:18px;padding:0 5px;border-radius:999px;background:var(--ds-accent);color:#fff;font:700 11px/18px var(--ds-font);text-align:center}",
  ".wh-spot-conf{width:7px;height:7px;border-radius:50%;flex:0 0 auto}",
  ".wh-spot-conf--ok{background:var(--ds-success)}.wh-spot-conf--warn{background:var(--ds-warn)}.wh-spot-conf--muted{background:var(--ds-ink-faint)}",
  ".wh-spot-dash{display:flex;flex-direction:column;gap:14px}",
  ".wh-spot-metrics{display:flex;flex-wrap:wrap;gap:10px}",
  ".wh-spot-metric{flex:1 1 100px;border:1px solid var(--ds-glass-border);background:rgba(255,255,255,.46);border-radius:var(--ds-radius-md);padding:11px 13px;display:flex;flex-direction:column;gap:4px}",
  ".wh-spot-metric-k{font:600 11px/1 var(--ds-font);color:var(--ds-ink-muted)}",
  ".wh-spot-metric-v{font:800 16px/1 var(--ds-font);color:var(--ds-ink)}",
  ".wh-spot-metric-v--big{font-size:22px;color:var(--ds-accent)}",
  ".wh-spot-bars{display:flex;align-items:flex-end;gap:4px;height:48px;padding:4px 2px;border-radius:var(--ds-radius-md);background:rgba(255,255,255,.4)}",
  ".wh-spot-bar{flex:1 1 auto;min-width:3px;border-radius:3px 3px 0 0;background:linear-gradient(180deg,#7c83ff,#b57bff)}",
  ".wh-spot-bubble{display:flex;flex-direction:column;gap:12px}",
  ".wh-spot-bubble-summary{margin:0;font:500 14px/1.6 var(--ds-font);color:var(--ds-ink);overflow-wrap:anywhere}",
  ".wh-spot-bubble-note{margin:0;font:500 12px/1.5 var(--ds-font);color:var(--ds-warn)}",
  ".wh-spot-know{display:flex;flex-direction:column;gap:12px}",
  ".wh-spot-know-bar{display:flex;gap:8px;align-items:center}",
  ".wh-spot-know-bar .wh-spot-freetext{flex:1 1 auto}",
  ".wh-spot-know-projects{display:flex;flex-wrap:wrap;gap:7px}",
  ".wh-spot-know-projects .wh-spot-reason[data-sel=\"true\"]{border-color:var(--ds-accent);color:var(--ds-accent);background:var(--ds-accent-soft)}",
  // 网盘 / 回放。
  ".wh-spot-file-icon{display:inline-flex;width:22px;height:22px;flex:0 0 auto;color:var(--ds-accent)}.wh-spot-file-icon svg{width:22px;height:22px}",
  ".wh-spot-drive-section{margin-top:6px}",
  ".wh-spot-run-dot{flex:0 0 auto;width:9px;height:9px;border-radius:50%;background:var(--ds-ink-faint)}",
  ".wh-spot-run-dot--running{background:var(--ds-success);box-shadow:0 0 0 3px var(--ds-success-soft);animation:ds-float 1.6s var(--ds-ease) infinite}",
  ".wh-spot-run-dot--queued{background:var(--ds-info)}",
  ".wh-spot-run-dot--waiting_for_user{background:var(--ds-warn);box-shadow:0 0 0 3px var(--ds-warn-soft)}",
  ".wh-spot-run-dot--failed{background:var(--ds-danger)}",
  ".wh-spot-trace{display:flex;flex-direction:column;gap:0;border-left:2px solid var(--ds-glass-border);padding-left:14px;margin-left:6px}",
  ".wh-spot-trace-step{position:relative;padding:8px 0}",
  ".wh-spot-trace-step::before{content:\"\";position:absolute;left:-19px;top:12px;width:8px;height:8px;border-radius:50%;background:var(--ds-accent)}",
  ".wh-spot-trace-phase{font:700 12.5px/1.3 var(--ds-font);color:var(--ds-ink)}",
  ".wh-spot-trace-out{margin-top:3px;font:500 12px/1.5 var(--ds-font);color:var(--ds-ink-muted);overflow-wrap:anywhere;white-space:pre-wrap}",
  // 看改动 diff。
  ".wh-spot-changes{display:flex;flex-direction:column;gap:10px}",
  ".wh-spot-change{border:1px solid var(--ds-glass-border);background:rgba(255,255,255,.42);border-radius:var(--ds-radius-md);padding:11px 13px}",
  ".wh-spot-change-head{display:flex;align-items:center;gap:8px}",
  ".wh-spot-change-path{font:600 12px/1.3 var(--ds-font);color:var(--ds-ink-muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
  ".wh-spot-change-sum{margin-top:7px;font:500 13px/1.5 var(--ds-font);color:var(--ds-ink-soft);overflow-wrap:anywhere}",
  ".wh-spot-diff{margin-top:9px;border-radius:var(--ds-radius-sm);overflow:hidden;font:500 11.5px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}",
  ".wh-spot-diff-line{padding:5px 9px;overflow-wrap:anywhere;white-space:pre-wrap}",
  ".wh-spot-diff-line--del{background:rgba(232,93,112,.12);color:#b3354a}",
  ".wh-spot-diff-line--add{background:rgba(31,175,134,.13);color:#137a5c}",
  ".wh-spot-checks{display:flex;flex-wrap:wrap;gap:7px}",
  ".wh-spot-check{font:600 11.5px/1 var(--ds-font);border-radius:7px;padding:5px 9px;background:rgba(255,255,255,.6);color:var(--ds-ink-muted)}",
  ".wh-spot-check--passed{background:var(--ds-success-soft);color:var(--ds-success)}",
  ".wh-spot-check--failed{background:var(--ds-danger-soft);color:var(--ds-danger)}",
  ".wh-spot-check--warning{background:var(--ds-warn-soft);color:var(--ds-warn)}",
  // 设置。
  ".wh-spot-set-group{display:flex;flex-direction:column;gap:8px}",
  ".wh-spot-set-label{font:600 12px/1 var(--ds-font);color:var(--ds-ink-muted)}",
  // 内联轻提示。
  ".wh-spot-toast{position:absolute;left:50%;bottom:14px;transform:translateX(-50%);max-width:calc(100% - 28px);z-index:5;display:flex;align-items:center;gap:8px;border-radius:var(--ds-radius-pill);padding:9px 15px;font:600 12.5px/1.3 var(--ds-font);color:#fff;background:rgba(40,32,70,.92);box-shadow:var(--ds-shadow-2);animation:ds-pop var(--ds-dur) var(--ds-spring) both;-webkit-app-region:no-drag}",
  ".wh-spot-toast--ok{background:linear-gradient(135deg,#1faf86,#34c79a)}",
  ".wh-spot-toast--error{background:linear-gradient(135deg,#e85d70,#ff9bb0)}",
  // #20：toast 退场动画——移除前先播一帧缩放淡出(translateX(-50%) 居中,关键帧须带上),不再硬删。
  ".wh-spot-toast--leaving{animation:ds-spot-toast-out var(--ds-dur-fast) var(--ds-ease) both}",
  "@keyframes ds-spot-toast-out{from{transform:translateX(-50%) scale(1);opacity:1}to{transform:translateX(-50%) scale(.94);opacity:0}}",
  // #18：内层面板也用真玻璃(背景模糊+饱和)而非纯白填充,与外层盒及 decision-deck 一致,强化「液态玻璃」层次。
  ".wh-spot-cap,.wh-spot-opt,.wh-spot-row,.wh-spot-metric,.wh-spot-change,.wh-spot-bars,.wh-spot-check{backdrop-filter:blur(13px) saturate(150%);-webkit-backdrop-filter:blur(13px) saturate(150%)}",
  // 尊重「减少动态效果」系统偏好：去掉装饰性位移/缩放，保留颜色提示（苹果级无障碍）。
  "@media (prefers-reduced-motion:reduce){.wh-spot-cap,.wh-spot-act,.wh-spot-back,.wh-spot-opt,.wh-spot-reason,a.wh-spot-row{transition-duration:.01ms!important}.wh-spot-cap:hover,.wh-spot-cap:active,.wh-spot-act:active,.wh-spot-back:active,.wh-spot-opt:hover,.wh-spot-opt:active,.wh-spot-reason:active,a.wh-spot-row:hover,a.wh-spot-row:active{transform:none}}"
].join("");
