// 金路径示例页（/api/pages/gold-path）的中→英文案对照表。
// 文案 locale 独占门禁：含汉字的字面量只许住在词典文件里，见 scripts/dev/check-ui-i18n.ts。

export const generatedEnglishCopy = new Map<string, string>([
  ["这份复盘包模板先按哪个口径做？", "Which direction should this review template use first?"],
  ["我会用会议纪要和网盘数据起草，先选一个最接近的方向。", "I will draft from meeting notes and drive data. Choose the closest direction first."],
  ["风险优先", "Risk first"],
  ["先列受阻的客户和需要你拍板的事。", "List blocked customers and items needing your decision first."],
  ["更适合发给管理者快速看重点。", "Better for managers who need the key points quickly."],
  ["进展优先", "Progress first"],
  ["先列本周完成、下周计划，再补风险。", "List this week's progress and next week's plan before risks."],
  ["更适合团队日常同步。", "Better for routine team sync."],
  ["数据优先", "Data first"],
  ["先放核心指标和趋势，再补文字说明。", "Show core metrics and trends before narrative notes."],
  ["更适合经营复盘，但需要更多数据校验。", "Better for operating reviews, with more data validation needed."],
  ["有特殊格式再补一句，不填也可以。", "Add format requirements only if needed."],
  ["需求", "Intent"],
  ["口径", "Scope"],
  ["草稿", "Draft"],
  ["审批", "Approval"],
  ["我找到了会议口径、网盘数据和客户格式偏好，足够起草第一版。", "I found meeting criteria, drive data, and format preferences, enough for a first draft."],
  ["用这些证据继续", "Use this evidence"],
  ["打开完整检索", "Open full search"],
  ["再问一个范围问题", "Ask another scope question"],
  ["本次运行已接近单次预算上限，我会保留回放并优先使用便宜模型继续。", "This run is close to its per-run budget. Keep replay and prefer a cheaper model next."],
  ["继续但降级模型", "Continue with a cheaper model"],
  ["查看预算", "View budget"],
  ["生成区域发布复盘包模板", "Generate regional launch review template"],
  ["我的今日 AI 预算", "My AI budget today"],
  ["团队今日 AI 预算", "Team AI budget today"],
  ["写入交付物前后都有还原点", "Restore points exist before and after deliverable writes"],
  ["这次变更申请已记入审计", "This change request is recorded in the audit trail"],
  ["查看变更", "View change"],
  ["打回", "Request changes"],
  ["区域发布复盘包模板已采纳", "Regional launch review template accepted"],
  ["我已经合并交付物，并留下了审计和回滚入口。", "I merged the deliverables and kept audit and rollback entry points."],
  ["查看交付物", "View deliverables"],
  ["查看回放", "View replay"],
  ["Cuu 等你审批《区域发布复盘包模板》", "Cuu is waiting for your review of the regional launch review template"],
  ["2 个交付物、3 条证据、可回滚；点同意后才会进入正式交付。", "2 deliverables, 3 evidence refs, reversible. It enters official delivery only after approval."],
  ["打回时请写明原因，Cuu 会带着它继续改。", "Say why you're sending it back — Cuu will use it in the next revision."],
  ["打开审批", "Open approval"],
  ["通过", "Approve"],
  ["Cuu 写好了区域发布复盘包模板", "Cuu drafted the regional launch review template"],
  ["请看一下这份非代码变更申请：2 个交付物、3 条证据、可回滚。", "Review this non-code change request: 2 deliverables, 3 evidence refs, reversible."],
  ["需要你决定采纳还是打回。", "Decide whether to accept it or request changes."],
  ["选择口径", "Choose scope"],
  ["区域发布复盘包模板", "Regional launch review template"],
  ["交付物已生成，等待审批。", "Deliverables are generated and waiting for approval."],
  ["先点一个复盘包口径，我再开始做。", "Choose a review direction before I start."],
  ["先点一个区域发布复盘包口径，我再开始做。", "Choose a regional launch review direction before I start."],
  ["采纳", "Approve"],
  ["打回并说明原因", "Request changes with a reason"],
  ["采纳进正式版", "Adopt into the official version"],
  ["复盘口径已确认", "Review scope confirmed"],
  ["每处改动都能单独查看", "Every change can be reviewed on its own"],
  ["这次花了多少一目了然", "The cost of this run is visible"]
]);
